<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DataAnggotaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('data_anggotas')->insert([
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],
            [
                'nik' => '9999',
                'image' => '',
                'nama' => 'Najwa syarifah',
                'jabatan' => 'Forman',
            ],

        ]);
    }
}
